#!/bin/bash

# Display usage if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Disable strict host key checking
scp_options="-o StrictHostKeyChecking=no"

# Transfer the file using scp to the user's home directory on the server
scp $scp_options -i "$ssh_key" "$237712-web-01" "$ubuntu@$server_54.165.43.95:~/"

echo "File transfer completed successfully."

